%startProgram

myTimer = timer('Name','MyTimer',               ...
                'Period',3,                 ... 
                'StartDelay',3,                 ... 
                'TasksToExecute',inf,           ... 
                'ExecutionMode','fixedSpacing'); 
            
myTimer.TimerFcn = {@(obj,event)shapePredict};
            
start(myTimer); 
